<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>asv_mavlink</name>
  <version>0.0.0</version>
  <description>Pacote de integracao com MAVLink e ArduPilot SITL</description>
  <maintainer email="michel@email.com">Michel Kleyton</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>geographic_msgs</exec_depend>
  <exec_depend>sensor_msgs_interfaces</exec_depend>
  <exec_depend>geometry_msgs_interfaces</exec_depend>
  <exec_depend>nav_msgs_interfaces</exec_depend>
  <exec_depend>std_msgs_interfaces</exec_depend>
  <exec_depend>mavros_msgs_interfaces</exec_depend>
  <exec_depend>tf2_ros_interfaces</exec_depend>
  <exec_depend>tf2_geometry_msgs_interfaces</exec_depend>
  <exec_depend>geographic_msgs_interfaces</exec_depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>